# Generated by Django 3.2.6 on 2021-08-31 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0005_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Clik Link Above To Read Blog Post...', max_length=255),
        ),
    ]
